# Generated by Django 4.2.13 on 2024-06-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='County',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
    ]
