# Generated by Django 4.2.13 on 2024-06-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_shipped',
            new_name='date_delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipped',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='delivery_address',
        ),
    ]
