# Generated by Django 4.2.13 on 2024-06-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_category_rename_pub_date_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
